### ISSUE TITLE
Using RecordEvent directly causes a nil panic

### ISSUE THREAD

**Issue by neetle** [dogmatiq/testkit#132]
The following test: 
```
func Test_Foo(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	t.Cleanup(cancel)
	g := NewGomegaWithT(t)

	db := getDB(ctx, t)

	adapter, err := pksql.New(db, &foo.Projection{}, &pkmysql.Driver{})
	g.Expect(err).To(Succeed())
	runner :=
		testkit.New(&app.App{Foo: adapter}).
			BeginContext(ctx, t,
				testkit.WithOperationOptions(
					engine.EnableProjections(true),
				)).EventRecorder()

	g.Expect(
		runner.RecordEvent(ctx, &event.Foo{}),
	).To(Succeed())
}

```

causes the following panic:

```
--- FAIL: Test_Foo (0.06s)
    --- FAIL: Test_Foo/bar (0.06s)
        handler_test.go:76: using db root@tcp(127.0.0.1:3306)/test_41b3dc841e3a11eba321acde48001122?sql_mode=%27%27 for Test_Foo/bar's readmodel
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x443efba]

goroutine 12 [running]:
testing.tRunner.func1.1(0x5368600, 0x6ca8270)
        /usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc0003eec60)
        /usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:944 +0x3f9
panic(0x5368600, 0x6ca8270)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:967 +0x15d
github.com/dogmatiq/testkit/engine.EventRecorder.RecordEvent(0x0, 0x0, 0x0, 0x0, 0x5a88ae0, 0xc0004bc000, 0x55e1f20, 0xc0006a42c0, 0xc0006a2101, 0xc0006a42c0)
        /Users/nathanial/go/pkg/mod/github.com/dogmatiq/testkit@v0.8.0/engine/recorder.go:25 +0x9a
github.com/example/project/foo_test.Test_Foo.func2(0xc0003eec60)
        /Users/nathanial/grit/github.com/example/project/foo_test.go:58 +0x39d
testing.tRunner(0xc0003eec60, 0xc00000ec60)
        /usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
        /usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1043 +0x357```

**Comment by jmalloc** [comment]
Thanks! As discussed on Slack this is because it wasn't used inside `Test.Call()`, however I do want to fix this to allow use of the test's event recorder (and command executor) before any assertion is made.

I'm sure this is what you were doing beforehand anyway, but `Test.Prepare(&event.Foo{})` should do what you need. See also #127 for upcoming changes to this API.

**Comment by jmalloc** [comment]
I have tried to come up a way to allow use of command executors and event recorders outside of `Call()` but was unable to settle on any behavior that seemed appropriate in all cases.

As of v0.13.5 this still panics, but it at least produces a more meaningful panic message.
